layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: VasilKotsev
  linkedin: vasil-kotsev
  # medium: @your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # youtube: your_username
  # instagram: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url

topics:
  - name: .NET Core (C#)
    web_url: https://github.com/dotnet/core
    image_url: https://pluralsight.imgix.net/paths/path-icons/csharp-e7b8fcd4ce.png

  - name: T-SQL & Microsoft SQL Server
    web_url: https://www.microsoft.com/en-us/sql-server
    image_url: http://www.zdnet.de/wp-content/uploads/2015/05/microsoft_sql-server-logo.png
    
  - name: ASP.NET Core
    web_url: https://github.com/aspnet/AspNetCore
    image_url: https://ih1.redbubble.net/image.366684650.5673/flat,550x550,075,f.u1.jpg
  
  - name: Blazor
    web_url: https://dotnet.microsoft.com/en-us/apps/aspnet/web-apps/blazor
    image_url: https://upload.wikimedia.org/wikipedia/commons/d/d0/Blazor.png

  - name: Angular
    web_url: https://angular.io/
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Angular_full_color_logo.svg/1200px-Angular_full_color_logo.svg.png

  - name: Microsoft Azure
    web_url: https://azure.microsoft.com/en-us/
    image_url: https://bornsql.ca/wp-content/uploads/2018/09/azurelogo.jpg
  
  - name: Docker
    web_url: https://www.docker.com/
    image_url: https://www.docker.com/wp-content/uploads/2022/03/vertical-logo-monochromatic.png.webp
